### ISSUE TITLE
How to subscribe Option Instruments

### ISSUE THREAD

**Issue by devbbsr123** [TradeViaPython/a3_aliceblue#3]
Dear Sir, 

Ho do I subscribe and unsubscribe options instruments? 
Like Banknifty 25Aug22 39500 CE for LTP. 

Kindly Share the examples. 

Thanks

**Comment by TradeViaPython** [comment]
import datetime

instrument= alice.get_instrument_for_fno("NFO", "BANKNIFTY", is_fut=False, expiry_date=datetime.date(2022, 8, 25), strike=39000, is_CE=True)

alice.subscribe([ instrument ])
alice.unsubscribe([ instrument ])

**Comment by devbbsr123** [comment]
Thanks Sir,
